services:
  db:
    image: couchdb:3.5
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
    ports:
      - 127.0.0.1:5984:5984
  ldap:
    image: ghcr.io/zakodium/ldap-with-users:1
    ports:
      - 127.0.0.1:1389:389
